--Rocket's Tricky Gym (Team Rocket Returns 90/109)
local scard,sid=aux.GetID()
function scard.initial_effect(c)
	aux.AddSetcode(c,SETNAME_ROCKETS)
	--stadium
	aux.EnableStadiumAttribute(c)
	--gain attack (damage)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(sid,0))
	e1:SetCategory(CATEGORY_POKEMON_ATTACK)
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetRange(LOCATION_INPLAY)
	e1:SetAttackCost(ENERGY_C)
	e1:SetTarget(aux.HintTarget)
	e1:SetOperation(scard.op1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e2:SetRange(LOCATION_STADIUM)
	e2:SetTargetRange(LOCATION_INPLAY,LOCATION_INPLAY)
	e2:SetTarget(aux.TargetBoolFunction(Card.IsSetCard,SETNAME_DARK,SETNAME_ROCKETS))
	e2:SetLabelObject(e1)
	c:RegisterEffect(e2)
end
--gain attack (damage)
function scard.op1(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_DAMAGE)
	local g=Duel.GetInPlayPokemon(1-tp):Select(tp,1,1,nil)
	if g:GetCount()==0 then return end
	Duel.HintSelection(g)
	Duel.AttackDamage(e,20,g:GetFirst(),false,false,false)
end
